cd few-shot-video-classification/ && CUDA_VISIBLE_DEVICES=1 python finetune_metatrain_w_knowledge.py --video_path /media/nvme1/linhanxi/data/k400/k400_CMNsplit/ \
--train_list_path data/kinetics100/data_splits/meta_train_filtered.txt \
--val_video_path /media/nvme1/linhanxi/data/k400/k400_CMNsplit/ \
--val_list_path data/kinetics100/data_splits/trainclasses_val_filtered.list \
--dataset kinetics \
--n_classes 400 \
--n_finetune_classes 64 \
--pretrain_path /media/hdd/sda1/linhanxi/pretrained_weights/few-shot-video-classification/fsv_pretrained_model/r25d34_sports1m.pth \
--model r2plus1d_w_knowledge \
--model_depth 34 \
--batch_size 32 \
--n_threads 4 \
--checkpoint 1 \
--val_every 1 \
--train_crop random \
--n_samples_for_each_video 8 \
--n_val_samples 10 \
--weight_decay 0.001 \
--layer_lr 0.001 0.001 0.001 0.001 0.001 0.1 \
--ft_begin_index 0 \
--result_path /media/hdd/sda1/linhanxi/exp/few-shot-vid-cls/finetune_kinetics/w_knowledge/v0.3_clsBugFix_embedOrig_dropout0.9_ablation_orig_ablation_CLIPvisfea \
--CLIP_visual_fea_reg "/home/linhanxi/home_data/fea_clip_ViT-B-16_unfolded_24frms/*" \
--proposals_fea_pth /home/linhanxi/nfs_mount/3090_media_sda1_linhanxi/data/CLIP_related/action_knowledge/proposal_fea_cache.pt \
--CLIP_visual_arch "ViT-B/16"  --clip_visfea_sampleNum 24 --is_w_knowledge --is_amp --dropout_w_knowledge 0.9 --this_launch_script $0 \
--ablation_orig --ablation_CLIPvisfea
 #--CLIP_visual_fea_preload